 const coffeList = [
    {
        price: 9.90,
        type: ['TRADICIONAL'],
        name: 'Expresso Tradicional',
        description: 'O tradicional café feito com água quente e grãos moídos',
        image: 'http://127.0.0.1:5173/src/assets/expressoTradicional.svg',
    },
    {
        price: 9.90,
        type: ['TRADICIONAL'],
        name: 'Expresso Americano',
        description: 'Expresso diluído, menos intenso que o tradicional',
        image: 'http://127.0.0.1:5173/src/assets/expressoAmericano.svg',
    },
    {
        price: 9.90,
        type: ['TRADICIONAL'],
        name: 'Expresso Cremoso',
        description: 'Café expresso tradicional com espuma cremosa',
        image: 'http://127.0.0.1:5173/src/assets/expressoCremoso.svg',
    },
    {
        price: 9.90,
        type: ['TRADICIONAL','GELADO'],
        name: 'Expresso Gelado',
        description: 'Bebida preparada com café expresso e cubos de gelo',
        image: 'http://127.0.0.1:5173/src/assets/expressoGelado.svg',
    },
    {
        price: 9.90,
        type: ['TRADICIONAL','COM LEITE'],
        name: 'Café com Leite',
        description: 'Meio a meio de expresso tradicional com leite vaporizado',
        image: 'http://127.0.0.1:5173/src/assets/cafeComLeite.svg',
    },
    {
        price: 9.90,
        type: ['TRADICIONAL','COM LEITE'],
        name: 'Latte',
        description: 'Uma dose de café expresso com o dobro de leite e espuma cremosa',
        image: 'http://127.0.0.1:5173/src/assets/latte.svg',
    },
    {
        price: 9.90,
        type: ['TRADICIONAL','COM LEITE'],
        name: 'Capuccino',
        description: 'Bebida com canela feita de doses iguais de café, leite e espuma',
        image: 'http://127.0.0.1:5173/src/assets/capuccino.svg',
    },
    {
        price: 9.90,
        type: ['TRADICIONAL','COM LEITE'],
        name: 'Macchiato',
        description: 'Café expresso misturado com um pouco de leite quente e espuma',
        image: 'http://127.0.0.1:5173/src/assets/macchiato.svg',
    },
    {
        price: 9.90,
        type: ['TRADICIONAL','COM LEITE'],
        name: 'Mocaccino',
        description: 'Café expresso com calda de chocolate, pouco leite e espuma',
        image: 'http://127.0.0.1:5173/src/assets/mocaccino.svg',
    },
    {
        price: 12.90,
        type: ['ESPECIAL','COM LEITE'],
        name: 'Chocolate Quente',
        description: 'Bebida feita com chocolate dissolvido no leite quente e café',
        image: 'http://127.0.0.1:5173/src/assets/chocolateQuente.svg',
    },
    {
        price: 9.90,
        type: ['EPECIAL', 'ALCÓLICO', 'GELADO'],
        name: 'Cubano',
        description: 'Drink gelado de café expresso com rum, creme de leite e hortelã',
        image: 'http://127.0.0.1:5173/src/assets/cubano.svg',
    },
    {
        price: 9.90,
        type: ['ESPECIAL'],
        name: 'Havaiano',
        description: 'Bebida adocicada preparada com café e leite de coco',
        image: 'http://127.0.0.1:5173/src/assets/havaiano.svg',
    },
    {
        price: 9.90,
        type: ['ESPECIAL'],
        name: 'Árabe',
        description: 'Bebida preparada com grãos de café árabe e especiarias',
        image: 'http://127.0.0.1:5173/src/assets/arabe.svg',
    },
    {
        price: 9.90,
        type: ['ESPECIAL', 'ALCÓLICA'],
        name: 'Irlandês',
        description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
        image: 'http://127.0.0.1:5173/src/assets/irlandes.svg',
    },
  

]
module.exports = coffeList